; Apio project configuration file.
; See https://fpgawars.github.io/apio/docs/project-file for details.

[common]
board = sipeed-tang-primer-20k
top-module = counter
default-testbench = counter_tb.v

[env:default]

; SRAM only (lost on power cycle). Does not write the NOR flash.
;   apio upload -e sram
[env:sram]
programmer-cmd = openFPGALoader --force-terminal-mode --verify -b tangprimer20k ${BIN_FILE}
