; Apio project file.
;
; This file defines the Apio project configuration.
; See https://fpgawars.github.io/apio/docs/project-file for available
; options.

[common]
board = alinx-ax7035
top-module = main

; Env for build with slow blink.
[env:blink-slow]
defines =
    N=25_000_000

; Env for build with fast blink.
[env:blink-fast]
defines =
    N=6_250_000

